# Portable release: statically link the C runtime so the executable runs on a clean Windows machine
# with no VC++ Redistributable installed. See AGENTS.md sec.20 ("Portable distribution").
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
